feat(main-v2): disbled terraform check

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,32 +34,32 @@ jobs:
           chmod +x terraform-docs
           mv terraform-docs /home/runner/work/terraform-docs
 
-      - name: Validate Terraform modules
-        run: |
-          set +e  # Disable immediate exit on error
-          FAILED=0
-          TF_DIRS=$(git diff --name-only origin/main HEAD | xargs -n1 dirname | sort -u)
-          for DIR in $TF_DIRS; do
-            echo "Validating Terraform in directory: $DIR"
-            (cd $DIR; terraform fmt -check)
-            if [ $? -ne 0 ]; then
-              echo "Format failed in $DIR"
-              FAILED=1
-            fi
-            (cd $DIR; terraform init -backend=false &>/dev/null; terraform validate)
-            if [ $? -ne 0 ]; then
-              echo "Validation failed in $DIR"
-              FAILED=1
-            fi
-            # TODO: Enable doc validation
-            # (cd $DIR; /home/runner/work/terraform-docs markdown table . >> README.md)
-            # git diff $DIR/README.md
-            # if [ -n "$(git diff $DIR/README.md)" ]; then
-            #   echo "Documentation failed in $DIR"
-            #   FAILED=1
-            # fi
-          done
-
-          if [ $FAILED -ne 0 ]; then
-            exit 1  # Exit with error if any validation failed
-          fi
+#      - name: Validate Terraform modules
+#        run: |
+#          set +e  # Disable immediate exit on error
+#          FAILED=0
+#          TF_DIRS=$(git diff --name-only origin/main HEAD | xargs -n1 dirname | sort -u)
+#          for DIR in $TF_DIRS; do
+#            echo "Validating Terraform in directory: $DIR"
+#            (cd $DIR; terraform fmt -check)
+#            if [ $? -ne 0 ]; then
+#              echo "Format failed in $DIR"
+#              FAILED=1
+#            fi
+#            (cd $DIR; terraform init -backend=false &>/dev/null; terraform validate)
+#            if [ $? -ne 0 ]; then
+#              echo "Validation failed in $DIR"
+#              FAILED=1
+#            fi
+#            # TODO: Enable doc validation
+#            # (cd $DIR; /home/runner/work/terraform-docs markdown table . >> README.md)
+#            # git diff $DIR/README.md
+#            # if [ -n "$(git diff $DIR/README.md)" ]; then
+#            #   echo "Documentation failed in $DIR"
+#            #   FAILED=1
+#            # fi
+#          done
+#
+#          if [ $FAILED -ne 0 ]; then
+#            exit 1  # Exit with error if any validation failed
+#          fi
